AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  borrowhub

Globals:
  Function:
    Timeout: 10
    Architectures:
      - arm64

Resources:
  BorrowHubbFunction:
    Type: AWS::Serverless::Function
    # --- CHANGE #1 IS HERE ---
    # This Metadata section tells SAM how to build your function.
    Metadata:
      BuildMethod: makefile
    Properties:
      # This now correctly points to your source code directory.
      # SAM will run the build in here.
      CodeUri: . 
      Handler: bootstrap
      Runtime: provided.al2
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: any
            Cors:
              AllowMethods: "'GET,POST,PUT,DELETE,OPTIONS'"
              AllowHeaders: "'Content-Type,Authorization'"
              AllowOrigin: "'*'"

Outputs:
  BorrowHubbApi:
    Description: "API Gateway endpoint URL for Prod stage for BorrowHubb function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"