AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  borrowhub

Globals:
  Function:
    Timeout: 10
    Architectures:
      - arm64

Resources:
  BorrowHubbApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      CorsConfiguration:
        AllowMethods:
          - GET
          - POST
          - OPTIONS
        AllowOrigins:
          - "*"
        AllowHeaders:
          - Content-Type
          - Authorization

  BorrowHubbFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: makefile
    Properties:
      CodeUri: . 
      Handler: bootstrap
      Runtime: provided.al2
      Events:
        ApiEvent:
          Type: HttpApi
          Properties:
            ApiId: !Ref BorrowHubbApi
            Path: /{proxy+}
            Method: ANY

Outputs:
  BorrowHubbApi:
    Description: "API Gateway endpoint URL for the BorrowHubb function"
    Value: !Sub "https://${BorrowHubbApi}.execute-api.${AWS::Region}.amazonaws.com/"