AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  borrowhub

  Sample SAM Template for borrowhub

Globals:
  Function:
    Timeout: 5
    MemorySize: 128

Resources:
  BorrowHubbFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      Architectures:
        - x86_64
      Events:
        # This event block tells SAM to create an API Gateway,
        # configure it as a proxy, and connect it to this Lambda.
        BorrowHubbApiEvent:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY
            # This creates a stage named 'Prod'.
            RestApiId:
              Ref: ApplicationApi
    Metadata:
      DockerTag: go1.x-v1
      DockerContext: ./
      Dockerfile: Dockerfile

  # Explicitly define the API so we can name the stage
  ApplicationApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod

Outputs:
  BorrowHubbApi:
    Description: "API Gateway endpoint URL for Prod stage for Borrow Hubb function"
    Value: !Sub "https://${ApplicationApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/items"
