AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  borrow-hub
  Backend API for the BorrowHub application

Globals:
  Function:
    Timeout: 5
    MemorySize: 128
  Api:
    Cors:
      AllowMethods: "'POST, GET, OPTIONS'"
      AllowHeaders: "'Content-Type, Authorization'"
      AllowOrigin: "'*'"

Resources:
  ItemsTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      TableName: items
      PrimaryKey:
        Name: id
        Type: String
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1

  UsersTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      TableName: users
      PrimaryKey:
        Name: email
        Type: String
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1

  BorrowHubbFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: main
      Runtime: go1.x
      Architectures:
        - x86_64
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref ItemsTable
        - DynamoDBCrudPolicy:
            TableName: !Ref UsersTable
      Environment:
        Variables:
          ITEMS_TABLE_NAME: !Ref ItemsTable
          USERS_TABLE_NAME: !Ref UsersTable
      Events:
        Api:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY
    Metadata:
      BuildMethod: go1.x

Outputs:
  BorrowHubApi:
    Description: "API Gateway endpoint URL for Prod stage for BorrowHub function"
    # This value is now dynamic and will always be correct
    Value: !Sub "https://eq2ydxqlwj.execute-api.us-east-1.amazonaws.com/Prod/items"
