# This file is an AWS SAM template that defines the cloud infrastructure for BorrowHubb.
# SAM (Serverless Application Model) is a framework for building serverless applications on AWS.

AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  BorrowHubb API
  This template defines the backend API function and the frontend S3 bucket.

Globals:
  Function:
    Timeout: 10 # Set a default timeout for all Lambda functions

Resources:
  # 1. The AWS Lambda Function that will run our Go backend code
  BorrowHubbApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: bootstrap
      Runtime: provided.al2
      # FIXED: Changed architecture to x86_64 to match the GitHub Actions build environment
      Architectures:
        - x86_64
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY

  # 2. The Amazon S3 Bucket that will host our static React frontend
  FrontendS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: index.html
      BucketName: !Sub "borrowhub-frontend-${AWS::AccountId}"

  # 3. A Bucket Policy to allow public access to the S3 website content
  FrontendS3BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref FrontendS3Bucket
      PolicyDocument:
        Statement:
          - Sid: PublicReadGetObject
            Effect: Allow
            Principal: '*'
            Action: s3:GetObject
            Resource: !Sub "arn:aws:s3:::${FrontendS3Bucket}/*"

Outputs:
  BorrowHubbApiEndpoint:
    Description: "API Gateway endpoint URL for our service"
    Value: !Sub "https://api.${AWS::Region}.amazonaws.com/Prod/{proxy+}"
  FrontendURL:
    Description: "URL for the hosted frontend website"
    Value: !GetAtt FrontendS3Bucket.WebsiteURL
