AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  borrowhub

  Sample SAM Template for borrowhub

Globals:
  Function:
    Timeout: 10
    Architectures:
      - arm64

Resources:
  BorrowHubbFunction:
    Type: AWS::Serverless::Function
    Properties:
      # The CodeUri will point to the zip file created by the Makefile
      CodeUri: build/main.zip
      Handler: bootstrap
      Runtime: provided.al2
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: any
            # --- THE FIX IS HERE ---
            # This section configures CORS to allow your frontend to call the API.
            Cors:
              AllowMethods: "'GET,POST,PUT,DELETE,OPTIONS'"
              AllowHeaders: "'Content-Type,Authorization'"
              AllowOrigin: "'*'" # This allows any website to call your API.
            # --- END OF FIX ---

Outputs:
  BorrowHubbApi:
    Description: "API Gateway endpoint URL for Prod stage for BorrowHubb function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"