AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  borrowhub

Globals:
  Function:
    Timeout: 10
    Architectures:
      - arm64

Resources:
  # --- CHANGE #1: Define the API as its own resource ---
  BorrowHubbHttpApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      # This is the correct location for the CORS configuration
      CorsConfiguration:
        AllowMethods:
          - GET
          - POST
          - OPTIONS
        AllowOrigins:
          - "*" # Allows all domains
        AllowHeaders:
          - Content-Type
          - Authorization

  # --- CHANGE #2: Define the function ---
  BorrowHubbFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: makefile
    Properties:
      CodeUri: . 
      Handler: bootstrap
      Runtime: provided.al2
      Events:
        # Link the function to ANY request on the API we defined above
        ApiEvent:
          Type: HttpApi
          Properties:
            Path: /{proxy+}
            Method: ANY
            ApiId:
              Fn::Ref: BorrowHubbHttpApi

Outputs:
  BorrowHubbApi:
    Description: "API Gateway endpoint URL for Prod stage for BorrowHubb function"
    Value:
      Fn::Sub: "https://${BorrowHubbHttpApi}.execute-api.${AWS::Region}.amazonaws.com/"