AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  borrowhub

  Sample SAM Template for borrowhub

Globals:
  Function:
    Timeout: 5
    MemorySize: 128

Resources:
  BorrowHubbFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      Architectures:
        - x86_64
      Events:
        BorrowHubbApi:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: any
    Metadata:
      DockerTag: go1.x-v1
      DockerContext: ./
      Dockerfile: Dockerfile

  # --- NEW: Explicitly define the API Gateway ---
  ApplicationApi:
    Type: AWS::Serverless::Api
    Properties:
      # This creates a stage named '$default' which does not appear in the URL path
      StageName: $default
      # Connect this API definition to our Lambda function
      DefinitionBody:
        swagger: '2.0'
        info:
          title: 
            Fn::Ref: AWS::StackName
        paths:
            x-amazon-apigateway-any-method:
              x-amazon-apigateway-integration:
                uri:
                  Fn::Sub: "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${BorrowHubbFunction.Arn}/invocations"
                passthroughBehavior: "when_no_match"
                httpMethod: "POST"
                httpMethod: "POST"
                type: "aws_proxy"
  BorrowHubbApi:
    Description: "API Gateway endpoint URL for the BorrowHubb function"
    # --- UPDATED: Get the URL from our new explicit API ---
    Value:
      Fn::Sub: "https://${ApplicationApi}.execute-api.${AWS::Region}.amazonaws.com/"
    # --- UPDATED: Get the URL from our new explicit API ---
    Value: !Sub "https://${ApplicationApi}.execute-api.${AWS::Region}.amazonaws.com/"