AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  BorrowHubb API
  This template defines the backend API function and the frontend S3 bucket.

Globals:
  Function:
    Timeout: 10

Resources:
  BorrowHubbApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      # FIXED: CodeUri now points to the built artifact location.
      CodeUri: .aws-sam/build/BorrowHubbApiFunction
      Handler: bootstrap
      Runtime: provided.al2
      Architectures:
        - x86_64
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY
    # This metadata tells 'sam build' how to build the code at the source path '.'
    Metadata:
      BuildMethod: makefile

  FrontendS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: index.html
      BucketName: !Sub "borrowhub-frontend-${AWS::AccountId}"
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false

  FrontendS3BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref FrontendS3Bucket
      PolicyDocument:
        Statement:
          - Sid: PublicReadGetObject
            Effect: Allow
            Principal: '*'
            Action: s3:GetObject
            Resource: !Sub "arn:aws:s3:::${FrontendS3Bucket}/*"

Outputs:
  BorrowHubbApiEndpoint:
    Description: "API Gateway endpoint URL for our service"
    Value: !Sub "https://api.${AWS::Region}.amazonaws.com/Prod/{proxy+}"
  FrontendURL:
    Description: "URL for the hosted frontend website"
    Value: !GetAtt FrontendS3Bucket.WebsiteURL
