AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  borrowhub

Globals:
  Function:
    Timeout: 10
    Architectures:
      - arm64

Resources:
  BorrowHubbFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: makefile
    Properties:
      CodeUri: . 
      Handler: bootstrap
      Runtime: provided.al2
      Events:
        # Define the API implicitly here
        ApiEvent:
          Type: HttpApi # Use HttpApi for v2 (faster, cheaper)
          Properties:
            # --- THE FIX IS HERE ---
            # This is the correct structure for CORS on an implicit HttpApi
            CorsConfiguration:
              AllowMethods:
                - GET
                - POST
                - OPTIONS
              AllowOrigins:
                - "*"
              AllowHeaders:
                - Content-Type
                - Authorization
            # --- END OF FIX ---
            # The function will be triggered for any path and method
            Path: /{proxy+}
            Method: ANY

Outputs:
  BorrowHubbApi:
    Description: "API Gateway endpoint URL for the BorrowHubb function"
    # The !Sub function constructs the final URL for us
    Value: !Sub "https://${ServerlessHttpApi}.execute-api.${AWS::Region}.amazonaws.com/"Prod/{proxy+}