AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  borrow-hub
  Backend API for the BorrowHub application

Globals:
  Function:
    Timeout: 15
    MemorySize: 128

Resources:
  BorrowHubbFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: bootstrap
      Runtime: provided.al2
      Architectures:
        - x86_64
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref ItemsTable
        - DynamoDBCrudPolicy:
            TableName: !Ref UsersTable
      Environment:
        Variables:
          ITEMS_TABLE_NAME: !Ref ItemsTable
          USERS_TABLE_NAME: !Ref UsersTable
      Events:
        Api:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY
            Cors:
              AllowMethods: "'GET,POST,OPTIONS'"
              AllowHeaders: "'Content-Type,Authorization'"
              AllowOrigin: "'*'"

  ItemsTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      TableName: items
      PrimaryKey:
        Name: id
        Type: String

  UsersTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      TableName: users
      PrimaryKey:
        Name: email
        Type: String

Outputs:
  BorrowHubApi:
    Description: "API Gateway endpoint URL for Prod stage for BorrowHub function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/prod"