name: Deploy Full Stack Application

on:
  push:
    branches:
      - main

jobs:
  deploy-backend:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    outputs:
      apiUrl: ${{ steps.get-api-url.outputs.apiUrl }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::260392369564:role/GitHubAction-AssumeRole-BorrowHubb
          aws-region: us-east-1

      - name: Set up Go and Cache Dependencies
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'
          cache-dependency-path: backend/go.sum

      - name: Install SAM CLI
        run: pip install aws-sam-cli

      # --- THE FIX IS HERE ---
      - name: Build and Deploy Backend
        run: |
          # Run sam build from the root, specifying the template file path
          sam build --template-file backend/template.yaml

          # Run sam deploy from the root, but change directory into backend first
          # This ensures deploy can find the built artifacts correctly
          cd backend
          sam deploy --no-confirm-changeset --no-fail-on-empty-changeset --stack-name BorrowHubb-API-Stack --s3-bucket aws-sam-cli-managed-default-samclisourcebucket-ramdczmoe5jg --capabilities CAPABILITY_IAM
      # --- END OF FIX ---

      - name: Get API Gateway URL
        id: get-api-url
        run: |
          API_URL=$(aws cloudformation describe-stacks --stack-name BorrowHubb-API-Stack --query "Stacks[0].Outputs[?OutputKey=='BorrowHubbApi'].OutputValue" --output text)
          echo "apiUrl=$API_URL" >> $GITHUB_OUTPUT

  deploy-frontend:
    runs-on: ubuntu-latest
    needs: deploy-backend
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::260392369564:role/GitHubAction-AssumeRole-BorrowHubb
          aws-region: us-east-1

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Frontend Dependencies
        run: |
          cd frontend
          npm ci

      - name: Build Frontend
        run: |
          cd frontend
          ./node_modules/.bin/vite build
        env:
          VITE_API_BASE_URL: ${{ needs.deploy-backend.outputs.apiUrl }}

      - name: Deploy Frontend to S3
        run: |
          aws s3 sync ./frontend/dist s3://borrowhub-frontend-260392369564 --delete