      # ... (previous steps are the same) ...

      - name: Build and Deploy Backend
        run: |
          # Define the ECR repository URI.
          # Replace this with the URI you copied from the AWS console.
          ECR_REPO_URI="260392369564.dkr.ecr.us-east-1.amazonaws.com/borrowhub"

          # Build the SAM application
          sam build --template-file backend/template.yaml

          # Deploy the SAM application.
          # We now add the --image-repository parameter.
          cd backend
          sam deploy \
            --no-confirm-changeset \
            --no-fail-on-empty-changeset \
            --stack-name BorrowHubb-API-Stack \
            --image-repository $ECR_REPO_URI \
            --capabilities CAPABILITY_IAM

      # ... (subsequent steps are the same) ...