# This file defines the CI/CD (Continuous Integration/Continuous Deployment) pipeline for BorrowHubb.
# It uses GitHub Actions to automatically build and deploy the application.

name: Deploy BorrowHubb to AWS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # --- FIX IS HERE ---
      # We are telling the action to look inside the 'backend' folder for our Go dependencies.
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'
          cache-dependency-path: backend/go.sum # Specify path to go.sum for caching

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Build and Deploy Backend with AWS SAM
        run: |
          cd backend
          sam build
          sam deploy --no-confirm-changeset --no-fail-on-empty-changeset

      - name: Build and Deploy Frontend
        run: |
          cd frontend
          npm install
          npm run build
          aws s3 sync ./dist s3://borrowhub-frontend-${{ secrets.AWS_ACCOUNT_ID }} --delete
