name: Deploy BorrowHubb to AWS
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Build and Deploy Backend with AWS SAM
        run: |
          cd backend
          # This command now runs the 'build' target in our Makefile
          # which creates bootstrap.zip
          sam build --beta-features
          # We now deploy the pre-packaged zip file
          sam deploy --stack-name BorrowHubb-API-Stack \
                     --capabilities CAPABILITY_IAM \
                     --resolve-s3 \
                     --no-confirm-changeset \
                     --no-fail-on-empty-changeset

      - name: Build and Deploy Frontend
        run: |
          cd frontend
          npm install
          npm run build
          aws s3 sync ./dist s3://borrowhub-frontend-${{ secrets.AWS_ACCOUNT_ID }} --delete
