name: Deploy Full Stack Application

on:
  push:
    branches:
      - main

jobs:
  deploy-backend:
    runs-on: ubuntu-latest
    permissions:
      id-token: write # Required for OIDC to connect to AWS
      contents: read
    outputs:
      # This makes the API URL available to other jobs
      apiUrl: ${{ steps.get-api-url.outputs.apiUrl }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          # This role should grant permissions to deploy SAM and CloudFormation
          role-to-assume: arn:aws:iam::260392369564:role/GitHubAction-AssumeRole-BorrowHubb
          aws-region: us-east-1

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Cache Go modules
        uses: actions/cache@v4
        with:
          path: ~/go/pkg/mod
          # --- FIX: Point to the correct go.sum location ---
          key: ${{ runner.os }}-go-${{ hashFiles('backend/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Install SAM CLI
        run: pip install aws-sam-cli

      - name: Build and Deploy Backend
        run: |
          cd backend
          sam build
          sam deploy --no-confirm-changeset --no-fail-on-empty-changeset --stack-name BorrowHubb-API-Stack --s3-bucket aws-sam-cli-managed-default-samclisourcebucket-ramdczmoe5jg --capabilities CAPABILITY_IAM

      - name: Get API Gateway URL
        id: get-api-url
        run: |
          API_URL=$(aws cloudformation describe-stacks --stack-name BorrowHubb-API-Stack --query "Stacks[0].Outputs[?OutputKey=='BorrowHubbApi'].OutputValue" --output text)
          echo "apiUrl=$API_URL" >> $GITHUB_OUTPUT

  deploy-frontend:
    runs-on: ubuntu-latest
    needs: deploy-backend # This job runs after the backend is successfully deployed
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          # This role should grant permissions to sync to the S3 bucket
          role-to-assume: arn:aws:iam::260392369564:role/GitHubAction-AssumeRole-BorrowHubb
          aws-region: us-east-1

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Frontend Dependencies
        run: |
          cd frontend
          npm install

      - name: Build Frontend
        run: |
          cd frontend
          # --- IMPROVEMENT: Use the API URL from the backend job ---
          npm run build
        env:
          VITE_API_BASE_URL: ${{ needs.deploy-backend.outputs.apiUrl }}

      - name: Deploy Frontend to S3
        run: |
          aws s3 sync ./frontend/dist s3://borrowhub-frontend-260392369564 --delete